#!/usr/bin/env php
<?php
error_reporting(7);
date_default_timezone_set('PRC');


$shortOpts = '';
$shortOpts .= 'c:';     // -c /etc/php-total/server.ini
$shortOpts .= 'l:';     // -l /var/log/php-total/php-total.log
$shortOpts .= 'vhd';    // -v debug模式.  -h : 帮助.  -d: 守护进程化

$longOpts = [
    'debug',        // --debug
    'help',         // --help
                    // 以下参数为内部调用task进程用, 无需用户设置
];

$options = getopt($shortOpts, $longOpts);

# 开启了debug
define('IS_DEBUG', isset($options['debug']) || isset($options['v']));

if (isset($options['help']) || isset($options['h']))
{
    goto help;
}

define('LOG_PATH', $options['l'] ?: null);

# 移除较大的log
if (LOG_PATH && is_file(LOG_PATH) && filesize(LOG_PATH) > 1024 * 1024 * 30)
{
    if (is_file(LOG_PATH.'.bak'))unlink(LOG_PATH.'.bak');
    rename(LOG_PATH, LOG_PATH.'.bak');
}


$red       = "\x1b[31m";
$lightBlue = "\x1b[36m";
$end       = "\x1b[39m";
$error     = "{$red}✕{$end}";

require __DIR__ . '/lib/DataObject.php';
require __DIR__ . '/lib/EtServer.php';
$server = new EtServer($options['c'], isset($options['d']), $options['l']);

$server->start();

return true;

# 输出帮助内容
help:
$file = basename(__FILE__);
echo <<<EOF
Usage: {$file} [options]
    -c PATH         config file path (default: /etc/php-total/server.ini)
    -l PATH         log file path
    -v, --debug     open debug mode

EOF;
exit;



function info($info)
{
    $beg = "\x1b[33m";
    $end = "\x1b[39m";
    $str = $beg . date("[Y-m-d H:i:s]") . "[info]{$end} - " . $info . "\n";

    if (LOG_PATH)
    {
        file_put_contents(LOG_PATH, $str, FILE_APPEND);
    }
    else
    {
        echo $str;
    }
}

function warn($info)
{
    $beg = "\x1b[31m";
    $end = "\x1b[39m";
    $str = $beg . date("[Y-m-d H:i:s]") . "[warn]{$end} - " . $info . "\n";

    if (LOG_PATH)
    {
        file_put_contents(LOG_PATH, $str, FILE_APPEND);
    }
    else
    {
        echo $str;
    }
}

function debug($info)
{
    if (!IS_DEBUG)return;

    $beg = "\x1b[34m";
    $end = "\x1b[39m";
    $str = $beg . date("[Y-m-d H:i:s]") . "[debug]{$end} - " . $info . "\n";

    if (LOG_PATH)
    {
        file_put_contents(LOG_PATH, $str, FILE_APPEND);
    }
    else
    {
        echo $str;
    }
}
