#!/bin/sh

TMP=$IFS
IFS='
'

for var in $(ps -u $LOGNAME |grep LogGate|grep -v grep|grep -v vim)
	do
#pid=echo $var |cut -c1-5
	pid=$(echo $var |awk '{ printf "%s ", $1}')
	pname=$(echo $var |awk '{ printf "%s ", $4}')

	#if kill -9 $pid
	if kill -2 $pid
	then 
	echo "stop $pname"
	else
	echo "can't stop $pname"
	fi
	done

cont=$(ps -u $LOGNAME |grep LogGate |grep -v grep|grep -v vim|wc -l)
	while [ $cont -gt 0 ]
	do
	echo "ServerNum:$cont"
	sleep 1
for var in $(ps -u $LOGNAME |grep LogGate |grep -v grep|grep -v vim)
	do
	pid=$(echo $var |awk '{ printf "%s ", $1}')
	kill -2 $pid
	done
cont=$(ps -u $LOGNAME |grep LogGate |grep -v grep|grep -v vim|wc -l)
	done

./go
